import { StyleSheet } from "react-native";

const COLORS = {
  bg: "#080808",
  card: "#121212",
  text: "#fff",
  muted: "rgba(255,255,255,0.55)",
  accent: "#ff5e00",
  border: "rgba(255,255,255,0.08)",
  green: "rgb(0, 255, 47)",
  strike: "#ff4444",
};

export const PricingSettingsLayoutStyles = StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  container: {
    paddingHorizontal: 16,
    paddingBottom: 120,
    paddingTop: 8,
  },
  logo: {
    width: 200,
    height: 48,
    alignSelf: "center",
    resizeMode: "contain",
    marginBottom: 16,
  },
  title: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: 0.5,
    lineHeight: 24,
    marginBottom: 20,
  },
  planCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 20,
    marginBottom: 20,
  },
  planName: {
    color: COLORS.accent,
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 12,
  },
  strikePrice: {
    fontSize: 13,
    textDecorationLine: "line-through",
    color: COLORS.strike,
    textAlign: "center",
  },
  priceRow: {
    alignItems: "center",
    marginBottom: 8,
  },
  newPrice: {
    color: COLORS.text,
    fontSize: 28,
    fontWeight: "800",
  },
  priceSuffix: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "600",
  },
  offBadge: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "600",
    marginTop: 4,
  },
  tagline: {
    color: COLORS.muted,
    fontSize: 12,
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 18,
  },
  helpText: {
    color: COLORS.green,
    fontSize: 11,
    textAlign: "center",
    marginTop: 12,
    lineHeight: 16,
  },
  featureRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 12,
  },
  featureText: {
    flex: 1,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "600",
  },
  available: {
    color: COLORS.green,
    fontSize: 12,
    fontWeight: "700",
  },
  termsNote: {
    color: COLORS.muted,
    fontSize: 12,
    textAlign: "center",
    marginTop: 16,
    lineHeight: 18,
  },
  checkoutNote: {
    color: COLORS.muted,
    fontSize: 13,
    textAlign: "center",
    marginTop: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  detailSection: {
    marginTop: 8,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  detailTitle: {
    color: COLORS.accent,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 12,
    textAlign: "center",
  },
  detailHeading: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 10,
  },
  detailBody: {
    color: COLORS.muted,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 12,
  },
  detailHighlight: {
    color: COLORS.strike,
    fontWeight: "700",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 4,
  },
  indepthBlock: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
  },
  indepthTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 8,
  },
  indepthP: {
    color: COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 8,
  },
});
